apiVersion: v1
kind: ServiceAccount   #this is a service account required to create service
metadata :
 name: admin
 namespace: default   
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata :    
 name: admin-role
rules :
 - apiGroups: ["*"]   #what kind of acces you want in api groups 
                      #pods service endpoints namepsaces
   resources : ["*"]
   verbs: ["*"] # get list watch actions to allow
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: admin-rolebinding
roleRef :
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: admin-role
subjects:
 - kind: ServiceAccount
   name: admin
   namespace: default