apiVersion: v1
kind: Namespace
metadata:
  name: roboshop

---
apiVersion: rbac.authorization.k8s.io/v1
Kind: Role
metadata: 
  namespace: roboshop
  name: roboshop-admin
rules:
- apiGroups: [""] #this indicates the core api group
  resources: ["*"]
  verbs: ["*"]  #actions on resources get list create read update delete
---
apiVersion: rbac.authorization.k8s.io/v1
Kind: RoleBinding
metadata:
  name: roboshop-admin
  namespace: roboshop-admin
subjects: #you can specify more than one subject
- Kind: User
  name: kops
  apiGroupp: rbac.authorization.k8s.io
roleref:
#"roleRef" specific the binding to a role /cluster role
  Kind: Role #this must be role or clusterole
  name: roboshop-admin #this msut match the name of the role or cluster role you wish to bind to 
  apiGroup: rbac.authorization.k8s.io