apiVersion: v1
kind: ServiceAccount
metadata :
 name: deshik
 namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata :
 name: deshik-role
rules :
 - apiGroups: [""]
   resources : ["pods", "services", "endpoints","namespaces"]
   verbs: ["get", "list", "watch"]

 - apiGroups: ["apps", "extensions"]
   resources : ["deployments", "replicasets", "daemonsets", "statefulsets"]
   verbs: ["get", "list", "watch"]

 - apiGroups: ["batch"]
   resources : ["jobs", "cronjobs"]
   verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: deshik-rolebinding
roleRef :
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: deshik-role
subjects:
 - kind: ServiceAccount
   name: deshik
   namespace: default